/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ejemplo.gui;

import com.ejemplo.dominio.Consultor;
import com.ejemplo.dominio.Empleado;
import com.ejemplo.dominio.Empresa;
import com.ejemplo.dominio.Trabajador;
import javax.swing.JOptionPane;

/**
 *
 * @author Nacho
 */
public class JDAgregar extends javax.swing.JDialog {

    private Empresa empresa;

    /**
     * Creates new form JDAgregar
     */
    public JDAgregar(java.awt.Frame parent, boolean modal, Empresa empresa) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        jcTrabajador.setSelectedIndex(0);
        this.empresa = empresa;
    }

    JDAgregar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcTrabajador = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jtLegajo = new javax.swing.JTextField();
        jtHorasExtra = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtFechaIngreso = new javax.swing.JTextField();
        jtPuesto = new javax.swing.JTextField();
        jtSueldo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jbAgregar = new javax.swing.JButton();
        jtCantidadHoras = new javax.swing.JTextField();
        jtValorHora = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jcTrabajador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 - Empleado", "2 - Consultor" }));
        jcTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcTrabajadorActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo de Trabajador");

        jLabel2.setText("Legajo");

        jLabel3.setText("Nombre");

        jLabel4.setText("Fecha Ingreso");

        jLabel5.setText("Puesto");

        jLabel6.setText("Sueldo");

        jLabel7.setText("Horas Extra");

        jLabel8.setText("Cantidad Horas");

        jLabel9.setText("Valor Hora");

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtCantidadHoras)
                    .addComponent(jtValorHora, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtLegajo)
                        .addComponent(jcTrabajador, 0, 175, Short.MAX_VALUE)
                        .addComponent(jtSueldo)
                        .addComponent(jtPuesto)
                        .addComponent(jtFechaIngreso)
                        .addComponent(jtNombre)
                        .addComponent(jtHorasExtra)))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jbAgregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtHorasExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtCantidadHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jtValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbAgregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcTrabajadorActionPerformed
        switch(jcTrabajador.getSelectedIndex()){
            case 0:
                jtSueldo.setEnabled(true);
                jtHorasExtra.setEnabled(true);
                jtCantidadHoras.setEnabled(false);
                jtValorHora.setEnabled(false);
                break;
            case 1:
                jtSueldo.setEnabled(false);
                jtHorasExtra.setEnabled(false);
                jtCantidadHoras.setEnabled(true);
                jtValorHora.setEnabled(true);
                break;
        }
    }//GEN-LAST:event_jcTrabajadorActionPerformed

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        Trabajador t;
        String nombre, fechaContratacion, puesto;
        int legajo;
        switch(jcTrabajador.getSelectedIndex()){
            case 0:
                int horasExtra;
                float sueldo;
                nombre = jtNombre.getText();
                fechaContratacion = jtFechaIngreso.getText();
                puesto = jtPuesto.getText();
                legajo = Integer.parseInt(jtLegajo.getText());
                horasExtra = Integer.parseInt(jtHorasExtra.getText());
                sueldo = Float.parseFloat(jtSueldo.getText());
                t = new Empleado(legajo, nombre, fechaContratacion, puesto, sueldo, horasExtra);
                break;
            case 1:
                nombre = jtNombre.getText();
                fechaContratacion = jtFechaIngreso.getText();
                puesto = jtPuesto.getText();
                legajo = Integer.parseInt(jtLegajo.getText());
                int cantidadHoras, valorHora;
                cantidadHoras = Integer.parseInt(jtCantidadHoras.getText());
                valorHora = Integer.parseInt(jtValorHora.getText());
                t = new Consultor(legajo, nombre, fechaContratacion, puesto, cantidadHoras, valorHora);
                break;
            default:
                t = null;
        }
        if(empresa.agregarEmpleado(t)){
            JOptionPane.showMessageDialog(this, "Trabajador Agregado!");
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo agregar Trabajador!");
        }
    }//GEN-LAST:event_jbAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JComboBox<String> jcTrabajador;
    private javax.swing.JTextField jtCantidadHoras;
    private javax.swing.JTextField jtFechaIngreso;
    private javax.swing.JTextField jtHorasExtra;
    private javax.swing.JTextField jtLegajo;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtPuesto;
    private javax.swing.JTextField jtSueldo;
    private javax.swing.JTextField jtValorHora;
    // End of variables declaration//GEN-END:variables
}
