/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ejemplo.gui;

import javax.swing.JOptionPane;

/**
 *
 * @author Nacho
 */
public class JFConversor extends javax.swing.JFrame {

    private float euro;
    private float dolar;
    /**
     * Creates new form JFConversor
     */
    public JFConversor() {
        initComponents();
        this.setLocationRelativeTo(null);
        euro = 91.0f;
        dolar = 79.25f;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtCantidad = new javax.swing.JTextField();
        jcMoneda = new javax.swing.JComboBox<>();
        jtResultante = new javax.swing.JTextField();
        jbFinalizar = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jbConvertir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de Monedas");

        jLabel1.setText("Ingrese Cantidad de Pesos");

        jLabel2.setText("Seleccione Moneda de Conversión");

        jLabel3.setText("Cantidad Resultante");

        jtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCantidadActionPerformed(evt);
            }
        });
        jtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtCantidadKeyTyped(evt);
            }
        });

        jcMoneda.setEditable(true);
        jcMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Dolar", "Euro" }));

        jtResultante.setEnabled(false);
        jtResultante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtResultanteActionPerformed(evt);
            }
        });

        jbFinalizar.setText("Finalizar");
        jbFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFinalizarActionPerformed(evt);
            }
        });

        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbConvertir.setText("Convertir");
        jbConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConvertirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbConvertir)
                        .addGap(18, 18, 18)
                        .addComponent(jbNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(jbFinalizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtCantidad)
                            .addComponent(jcMoneda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtResultante))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtResultante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbFinalizar)
                    .addComponent(jbNuevo)
                    .addComponent(jbConvertir))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCantidadActionPerformed
        
    }//GEN-LAST:event_jtCantidadActionPerformed

    private void jbFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFinalizarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbFinalizarActionPerformed

    private void jtResultanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtResultanteActionPerformed
        
    }//GEN-LAST:event_jtResultanteActionPerformed

    private void jbConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConvertirActionPerformed
        // TODO add your handling code here:
        try{
            if (jcMoneda.getSelectedIndex()==0 || (jtCantidad.getText().equals(""))){
            JOptionPane.showMessageDialog(this, "Ingrese Valores");
        } else if((jcMoneda.getSelectedIndex() == 1) && (!jtCantidad.getText().equals(""))){
            jtResultante.setText(this.cantidadDolar());
        } else if (jcMoneda.getSelectedIndex()==2 && (!jtCantidad.getText().equals(""))){
            jtResultante.setText(this.cantidadEuro());
        } 
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Valor no permitido!");
        }
    }//GEN-LAST:event_jbConvertirActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        // TODO add your handling code here:
        jtCantidad.setText("");
        jtResultante.setText("");
        jcMoneda.setSelectedIndex(0);
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCantidadKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if (!Character.isDigit(car) && car !='.') {
            evt.consume();
        }
    }//GEN-LAST:event_jtCantidadKeyTyped

    private float cantidad(){
        return Float.parseFloat(jtCantidad.getText());
    }
    
    private String cantidadDolar(){
        return Float.toString(this.cantidad() / dolar);
    }
    
    private String cantidadEuro(){
        return Float.toString(this.cantidad() / euro);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbConvertir;
    private javax.swing.JButton jbFinalizar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JComboBox<String> jcMoneda;
    private javax.swing.JTextField jtCantidad;
    private javax.swing.JTextField jtResultante;
    // End of variables declaration//GEN-END:variables
}
